### ISSUE TITLE
dbeep doesn't work if /bin/sh is not /bin/bash

### ISSUE THREAD

**Issue by Mathiasdm** [patrickdepinguin/dbeep#1]
For example on Ubuntu, /bin/sh maps to dash instead of bash.

**Comment by Zuccace** [comment]
dash is very plain shell and afaik does not have support for arrays, which are the requirement for dbeep.
IIRC dash's main target is to be POSIX shell compatible.

**Comment by patrickdepinguin** [comment]
Problem 'fixed' by explicitly requesting bash. Thanks for reporting!
